### PR TITLE
Fix node selector - so it stops trying to run on windows nodes

### PR DESCRIPTION
**Pull request by TJM**
Sorry, this one continues from my previous PR. If I need to rebase to fix that, let me know.

### CODE REVIEW

**Comment by TJM** [comment]
I removed the commit to do with namespaces, so this one is now stand-alone.

**Comment by TJM** [comment]
Some of this will need to be rebased if we pull the "Templatify" code first... I think this will come down to a default "nodeSelector" (whether or not it should exist)

Also, whether it should use "beta.kubernetes.io" or just "kubernetes.io" ?

```
nodeSelector:
  beta.kubernetes.io/arch: amd64
  beta.kubernetes.io/os: linux
```

vs

```
nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux
```

**Comment by TJM** [comment]
Can this software run on anything except linux/amd64? I realize hybrid kubernetes clusters are not very common, but unless the daemonset has a windows image (it didn't seem to), I believe it should be restricted to run on Linux nodes.

**Comment by cormachogan** [comment]
Yep - Linux only AFAIK. There is some talk of Windows support, but I have no idea how far out that is.

**Comment by mylesagray** [comment]
Closing as repo in new location - feel free to reopen there: https://github.com/vsphere-tmm/helm-charts

**Pull request closed without merging**
